### PR TITLE
feat(conventionalChangelogWriter): async transform function supported.

### PR DESCRIPTION
**Pull request by pjpsoares**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 36e3e0ff4063a948f5a301f3bb528aee5dfe8620
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by stevemao** [comment]
Why don't you just force push it instead of opening and closing issues?

**Comment by stevemao** [comment]
@pjpsoares http://stackoverflow.com/questions/5509543/how-do-i-properly-force-a-git-push

**Comment by pjpsoares** [comment]
I've tried that and as I struggled a bit I thought it would just be easier to create a new pull request. Just stupid I guess... Sorry about the confusion.

**Comment by stevemao** [comment]
You can just rebase when everything's done

**Pull request closed without merging**
