### PR TITLE
feat(conventionalChangelogWriter): async transform function supported.

### PR DESCRIPTION
**Pull request by pjpsoares**

### CODE REVIEW

**Comment by stevemao** [comment]
My comments in #11 still applies.

**Comment by stevemao** [comment]
Also please don't close and open issues as it is very noisy and we would lose track of the comments. Use git properly.

**Comment by pjpsoares** [comment]
Meaning that you'll leave it open a little longer, right?

**Comment by stevemao** [comment]
> Does it work with other promise implementation? Especially native promise because I think it'll be widely used.

**Comment by pjpsoares** [comment]
It will work with every promise implementation. From Q documentation the Q(): "Wraps an object that might be a value or a (3rd party) then-able promise into a $q promise. This is useful when you are dealing with an object that might or might not be a promise, or if the promise comes from a source that can't be trusted."

**Comment by stevemao** [comment]
Can you add some tests to prove it works with other promise implementations? Sorry I've been very busy recently. Much appreciated.

**Comment by hutson** [comment]
We're closing this pull request out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the pull request against the `conventional-changelog` mono-repository.

**Pull request closed without merging**
