### PR TITLE
conventionalChangelogWriter

### PR DESCRIPTION
**Pull request by pjpsoares**
changing conventionalChangelogWriter so the transform function passed to it can return a promise.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 8083c57ab7136ee4e30ef2e33786b62e1e76785f
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by stevemao** [comment]
Build fails. Can you fix it?

**Comment by stevemao** [comment]
Related tests are missing.
Can you also add an example how you might use it in the doc?

**Comment by pjpsoares** [comment]
I'm having some issues running this agains Windows. I've managed to fix the jshint and jscs issues, struggling to fix the tests, but will try to push a fix today.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 300b4d3b8cc78b61369ad623431a63292c49ec4f
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by pjpsoares** [comment]
It's a merge message that's giving a warning. What do you suggest for fixing this?

**Comment by stevemao** [comment]
I'll keep this open for a while and see how people like it. A few notes:
1. Does it work with other promise implementation? Especially native promise because I think it'll be widely used.
2. I only use Q or Bluebird internally so users don't have to use a specific promise implementation.

**Comment by stevemao** [comment]
Also the commit message should comply with the angular convention. Each commit should just do one thing. I guess you need to squash your commits.

**Comment by pjpsoares** [comment]
From their documentation Q(): "Wraps an object that might be a value or a (3rd party) then-able promise into a $q promise. This is useful when you are dealing with an object that might or might not be a promise, or if the promise comes from a source that can't be trusted."

**Comment by pjpsoares** [comment]
I'll open a new pull request.

**Comment by stevemao** [comment]
You can just force push to this one

**Pull request closed without merging**
